name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/appuio/mastodon-openshift/mastodon:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}