name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Mastodon tags
        id: mastodon-tag
        run: |
          tag=$(grep FROM Dockerfile | cut -c 35-40)
          echo "TAG=$tag" >> $GITHUB_OUTPUT
      
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          tags: |
            ghcr.io/appuio/mastodon-openshift/mastodon:latest
            ghcr.io/appuio/mastodon-openshift/mastodon:${{ steps.mastodon-tag.outputs.TAG }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}